// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
// Generated by `npm run sync` from the stepup-labs submodule. Do not hand-edit.
import sidebar from './src/sidebar.generated.json' with { type: 'json' };

// GitHub Pages serves a project repo under a subpath (/<repo>). The deploy
// workflow sets SITE and BASE; local dev leaves them unset and serves at root.
// For a custom domain (docs.yourdomain.com), set SITE to it and BASE to '/'.
export default defineConfig({
  site: process.env.SITE,
  base: process.env.BASE || '/',
  integrations: [
    starlight({
      title: 'SUTA Labs Docs',
      description:
        'Step-by-step database labs - tested on real servers, documented for beginners.',
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/hapi-suta/stepup-labs',
        },
      ],
      // Students follow steps in order - keep headings shallow in the right-hand ToC.
      tableOfContents: { minHeadingLevel: 2, maxHeadingLevel: 3 },
      sidebar: [
        {
          label: 'PostgreSQL',
          // Built by scripts/sync-content.ts: modules -> Concepts / Build / Use / Survive.
          items: sidebar,
        },
      ],
    }),
  ],
});
